const POINTS = {
  WIN_POINTS: 3,
  LOSE_POINTS: 0,
  DRAW_POINTS: 1,
  WIN_ALT_POINTS: 5,
  LOSE_ALT_POINTS: 1,
  DRAW_ALT_POINTS: 3,
};

const NUMBER_OF_TEAMS_PER_GROUP = 6;
const NUMBER_OF_GROUPS = 2;
const NUMBER_OF_MATCHES = 30;

module.exports = {
  POINTS,
  NUMBER_OF_TEAMS_PER_GROUP,
  NUMBER_OF_GROUPS,
  NUMBER_OF_MATCHES,
};
